TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

INCLUDEPATH += gsl-an \
    include \
    include/astrometry \
    libkd \
    qfits-an\
    solver \
    util \
    /usr/include/cairo


LIBS += -lcfitsio
LIBS += -L/usr/lib/x86_64-linux-gnu/libcairo.so

DEFINES += _GNU_SOURCE
LIBS += -ldl
QMAKE_LFLAGS += -rdynamic
QMAKE_LFLAGS += -Wl,--start-group -ldl -Wl,--end-group

SOURCES += \
    gsl-an/blas/blas.c \
    gsl-an/block/block.c \
    gsl-an/block/block_source.c \
    gsl-an/block/init_block.c \
    gsl-an/cblas/caxpy.c \
    gsl-an/cblas/ccopy.c \
    gsl-an/cblas/cdotc_sub.c \
    gsl-an/cblas/cdotu_sub.c \
    gsl-an/cblas/cgemm.c \
    gsl-an/cblas/cgemv.c \
    gsl-an/cblas/cgerc.c \
    gsl-an/cblas/cgeru.c \
    gsl-an/cblas/chemm.c \
    gsl-an/cblas/chemv.c \
    gsl-an/cblas/cher.c \
    gsl-an/cblas/cher2.c \
    gsl-an/cblas/cher2k.c \
    gsl-an/cblas/cherk.c \
    gsl-an/cblas/cscal.c \
    gsl-an/cblas/csscal.c \
    gsl-an/cblas/cswap.c \
    gsl-an/cblas/csymm.c \
    gsl-an/cblas/csyr2k.c \
    gsl-an/cblas/csyrk.c \
    gsl-an/cblas/ctrmm.c \
    gsl-an/cblas/ctrmv.c \
    gsl-an/cblas/ctrsm.c \
    gsl-an/cblas/ctrsv.c \
    gsl-an/cblas/dasum.c \
    gsl-an/cblas/daxpy.c \
    gsl-an/cblas/dcopy.c \
    gsl-an/cblas/ddot.c \
    gsl-an/cblas/dgemm.c \
    gsl-an/cblas/dgemv.c \
    gsl-an/cblas/dger.c \
    gsl-an/cblas/dnrm2.c \
    gsl-an/cblas/drot.c \
    gsl-an/cblas/drotg.c \
    gsl-an/cblas/drotm.c \
    gsl-an/cblas/drotmg.c \
    gsl-an/cblas/dscal.c \
    gsl-an/cblas/dsdot.c \
    gsl-an/cblas/dswap.c \
    gsl-an/cblas/dsymm.c \
    gsl-an/cblas/dsymv.c \
    gsl-an/cblas/dsyr.c \
    gsl-an/cblas/dsyr2.c \
    gsl-an/cblas/dsyr2k.c \
    gsl-an/cblas/dsyrk.c \
    gsl-an/cblas/dtrmm.c \
    gsl-an/cblas/dtrmv.c \
    gsl-an/cblas/dtrsm.c \
    gsl-an/cblas/dtrsv.c \
    gsl-an/cblas/dzasum.c \
    gsl-an/cblas/dznrm2.c \
    gsl-an/cblas/hypot.c \
    gsl-an/cblas/icamax.c \
    gsl-an/cblas/idamax.c \
    gsl-an/cblas/isamax.c \
    gsl-an/cblas/izamax.c \
    gsl-an/cblas/sasum.c \
    gsl-an/cblas/saxpy.c \
    gsl-an/cblas/scasum.c \
    gsl-an/cblas/scnrm2.c \
    gsl-an/cblas/scopy.c \
    gsl-an/cblas/sdot.c \
    gsl-an/cblas/sdsdot.c \
    gsl-an/cblas/sgemm.c \
    gsl-an/cblas/sgemv.c \
    gsl-an/cblas/sger.c \
    gsl-an/cblas/snrm2.c \
    gsl-an/cblas/srot.c \
    gsl-an/cblas/srotg.c \
    gsl-an/cblas/srotm.c \
    gsl-an/cblas/srotmg.c \
    gsl-an/cblas/sscal.c \
    gsl-an/cblas/sswap.c \
    gsl-an/cblas/ssymm.c \
    gsl-an/cblas/ssymv.c \
    gsl-an/cblas/ssyr.c \
    gsl-an/cblas/ssyr2.c \
    gsl-an/cblas/ssyr2k.c \
    gsl-an/cblas/ssyrk.c \
    gsl-an/cblas/strmm.c \
    gsl-an/cblas/strmv.c \
    gsl-an/cblas/strsm.c \
    gsl-an/cblas/strsv.c \
    gsl-an/cblas/xerbla.c \
    gsl-an/cblas/zaxpy.c \
    gsl-an/cblas/zcopy.c \
    gsl-an/cblas/zdotc_sub.c \
    gsl-an/cblas/zdotu_sub.c \
    gsl-an/cblas/zdscal.c \
    gsl-an/cblas/zgemm.c \
    gsl-an/cblas/zgemv.c \
    gsl-an/cblas/zgerc.c \
    gsl-an/cblas/zgeru.c \
    gsl-an/cblas/zhemm.c \
    gsl-an/cblas/zhemv.c \
    gsl-an/cblas/zher.c \
    gsl-an/cblas/zher2.c \
    gsl-an/cblas/zher2k.c \
    gsl-an/cblas/zherk.c \
    gsl-an/cblas/zscal.c \
    gsl-an/cblas/zswap.c \
    gsl-an/cblas/zsymm.c \
    gsl-an/cblas/zsyr2k.c \
    gsl-an/cblas/zsyrk.c \
    gsl-an/cblas/ztrmm.c \
    gsl-an/cblas/ztrmv.c \
    gsl-an/cblas/ztrsm.c \
    gsl-an/cblas/ztrsv.c \
    gsl-an/err/error.c \
    gsl-an/err/stream.c \
    gsl-an/err/strerror.c \
    gsl-an/linalg/apply_givens.c \
    gsl-an/linalg/bidiag.c \
    gsl-an/linalg/cholesky.c \
    gsl-an/linalg/givens.c \
    gsl-an/linalg/householder.c \
    gsl-an/linalg/lu.c \
    gsl-an/linalg/qr.c \
    gsl-an/linalg/svd.c \
    gsl-an/linalg/svdstep.c \
    gsl-an/matrix/copy_matrix.c \
    gsl-an/matrix/init_matrix.c \
    gsl-an/matrix/matrix.c \
    gsl-an/matrix/rowcol_matrix.c \
    gsl-an/matrix/submatrix_matrix.c \
    gsl-an/matrix/swap_matrix.c \
    gsl-an/matrix/view_matrix.c \
    gsl-an/multiroots/broyden.c \
    gsl-an/multiroots/convergence.c \
    gsl-an/multiroots/dnewton.c \
    gsl-an/multiroots/dogleg.c \
    gsl-an/multiroots/enorm.c \
    gsl-an/multiroots/fdfsolver.c \
    gsl-an/multiroots/fdjac.c \
    gsl-an/multiroots/fsolver.c \
    gsl-an/multiroots/gnewton.c \
    gsl-an/multiroots/hybrid.c \
    gsl-an/multiroots/hybridj.c \
    gsl-an/multiroots/newton.c \
    gsl-an/permutation/init_permutation.c \
    gsl-an/permutation/permutation.c \
    gsl-an/permutation/permute.c \
    gsl-an/permutation/permute_source.c \
    gsl-an/sys/coerce.c \
    gsl-an/sys/fdiv.c \
    gsl-an/sys/infnan.c \
    gsl-an/sys/ldfrexp.c \
    gsl-an/vector/copy_vector.c \
    gsl-an/vector/init_vector.c \
    gsl-an/vector/oper.c \
    gsl-an/vector/oper_source_vector.c \
    gsl-an/vector/oper_complex_source.c \
    gsl-an/vector/prop_vector.c \
    gsl-an/vector/subvector.c \
    gsl-an/vector/subvector_source.c \
    gsl-an/vector/swap_vector.c \
    gsl-an/vector/vector.c \
    libkd/checktree.c \
    libkd/dualtree.c \
    libkd/dualtree_nearestneighbour.c \
    libkd/dualtree_rangesearch.c \
    libkd/kdint_ddd.c \
    libkd/kdint_dds.c \
    libkd/kdint_ddu.c \
    libkd/kdint_dss.c \
    libkd/kdint_duu.c \
    libkd/kdint_fff.c \
    libkd/kdint_lll.c \
    libkd/kdtree.c \
    libkd/kdtree_dim.c \
    libkd/kdtree_fits_io.c \
    libkd/kdtree_internal.c \
    libkd/kdtree_internal_dists.c \
    libkd/kdtree_internal_fits.c \
    libkd/kdtree_mem.c \
    qfits-an/anqfits.c \
    qfits-an/md5.c \
    qfits-an/qfits_byteswap.c \
    qfits-an/qfits_card.c \
    qfits-an/qfits_convert.c \
    qfits-an/qfits_error.c \
    qfits-an/qfits_float.c \
    qfits-an/qfits_header.c \
    qfits-an/qfits_image.c \
    qfits-an/qfits_md5.c \
    qfits-an/qfits_memory.c \
    qfits-an/qfits_rw.c \
    qfits-an/qfits_table.c \
    qfits-an/qfits_time.c \
    qfits-an/qfits_tools.c \
    gsl-an/vector/init_source_vector.c \
    gsl-an/vector/copy_source_vector.c \
    gsl-an/vector/prop_source_vector.c \
    solver/agreeable.c \
    solver/allquads-main.c \
    solver/allquads.c \
    solver/augment-xylist-main.c \
    solver/augment-xylist.c \
    solver/build-index-main.c \
    solver/build-index.c \
    solver/catalog.c \
    solver/catalog_analysis.c \
    solver/certifiable.c \
    solver/checkquads.c \
    solver/codefile.c \
    solver/codeprojections.c \
    solver/codetree-main.c \
    solver/codetree.c \
    solver/control-program.c \
    solver/create-scamp-catalog.c \
    solver/cut-table.c \
    solver/diffractionFlag_check.c \
    solver/engine-main.c \
    solver/engine.c \
    solver/fits-guess-scale-main.c \
    solver/fits-guess-scale.c \
    solver/fitscopy.c \
    solver/get-wcs.c \
    solver/hpgrid.c \
    solver/hpowned.c \
    solver/hpquads-main.c \
    solver/hpquads.c \
    solver/image2xy-files.c \
    solver/image2xy-main.c \
    solver/imarith.c \
    solver/imcopy.c \
    solver/imstat.c \
    solver/index-info.c \
    solver/index-stats.c \
    solver/index-to-table.c \
    solver/keirthing.c \
    solver/listhead.c \
    solver/liststruc.c \
    solver/local-index.c \
    solver/lsfile.c \
    solver/merge-index-main.c \
    solver/merge-index.c \
    solver/mergesolved.c \
    solver/modhead.c \
    solver/new-wcs-main.c \
    solver/new-wcs.c \
    solver/onefield.c \
    solver/pnpoly.c \
    solver/printsolved.c \
    solver/quad-builder.c \
    solver/quad-utils.c \
    solver/quadcenters.c \
    solver/quadidx.c \
    solver/quadscales.c \
    solver/quadsperstar.c \
    solver/query-starkd.c \
    solver/randcat.c \
    solver/rdls2hpls.c \
    solver/resort-xylist-main.c \
    solver/resort-xylist.c \
    solver/setsolved.c \
    solver/solve-field.c \
    solver/solvedfile.c \
    solver/solver.c \
    solver/solverutils.c \
    solver/spike_join.c \
    solver/startree-main.c \
    solver/startree.c \
    solver/startree2rdls.c \
    solver/subwcs.c \
    solver/tablist.c \
    solver/tabmerge.c \
    solver/test-solver-2.c \
    solver/test-solver.c \
    solver/test_codefile.c \
    solver/test_multiindex2.c \
    solver/test_predistort.c \
    solver/test_resort-xylist.c \
    solver/test_solverutils.c \
    solver/test_tweak.c \
    solver/test_xscale.c \
    solver/threadtest.c \
    solver/tweak.c \
    solver/tweak2.c \
    solver/uniformize-catalog-main.c \
    solver/uniformize-catalog.c \
    solver/unpermute-quads-main.c \
    solver/unpermute-quads.c \
    solver/unpermute-stars-main.c \
    solver/unpermute-stars.c \
    solver/verify.c \
    solver/verify2.c \
    solver/wcs-grab.c \
    util/an-endian.c \
    util/an-fitstopnm.c \
    util/an-opts.c \
    util/anwcs.c \
    util/bl-nl-sort.c \
    util/bl-nl.c \
    util/bl-sort.c \
    util/bl.c \
    util/bt.c \
    util/coadd-main.c \
    util/coadd.c \
    util/codekd.c \
    util/convolve-image.c \
    util/ctmf.c \
    util/cutest.c \
    util/dallpeaks.c \
    util/datalog.c \
    util/dcen3x3.c \
    util/dfind.c \
    util/dfind2.c \
    util/dmedsmooth.c \
    util/dobjects.c \
    util/downsample-fits.c \
    util/dpeaks.c \
    util/dselip.c \
    util/dsigma.c \
    util/dsmooth.c \
    util/eigen-math-c.c \
    util/errors.c \
    util/fileutils.c \
    util/fit-wcs-main.c \
    util/fit-wcs.c \
    util/fits-column-merge.c \
    util/fits-flip-endian.c \
    util/fitsbin.c \
    util/fitsfile.c \
    util/fitsgetext.c \
    util/fitsioutils.c \
    util/fitstable.c \
    util/get-healpix.c \
    util/gslutils.c \
    util/healpix-utils.c \
    util/healpix.c \
    util/histogram.c \
    util/histogram2d.c \
    util/hpsplit.c \
    util/image2xy.c \
    util/index.c \
    util/indexset.c \
    util/intmap.c \
    util/ioutils.c \
    util/log.c \
    util/matchfile.c \
    util/matchobj.c \
    util/mathutil.c \
    util/md5_util.c \
    util/multiindex.c \
    util/pad-file.c \
    util/permutedsort.c \
    util/qidxfile.c \
    util/qsort_reentrant.c \
    util/quadfile.c \
    util/rdlist.c \
    util/resample-main.c \
    util/resample.c \
    util/scamp-catalog.c \
    util/scamp.c \
    util/search-index.c \
    util/simplexy.c \
    util/sip-utils.c \
    util/sip.c \
    util/sip_qfits.c \
    util/sparsematrix.c \
    util/starkd.c \
    util/starutil.c \
    util/starxy.c \
    util/subtable.c \
    util/tabsort-main.c \
    util/tabsort.c \
    util/tic.c \
    util/tpv.c \
    util/wcs-match.c \
    util/wcs-pv2sip-main.c \
    util/wcs-pv2sip.c \
    util/wcs-rd2xy-main.c \
    util/wcs-rd2xy.c \
    util/wcs-resample-main.c \
    util/wcs-resample.c \
    util/wcs-to-tan.c \
    util/wcs-xy2rd-main.c \
    util/wcs-xy2rd.c \
    util/wcsinfo.c \
    util/xylist.c \
    memory.c \
    solver/verify-main.c

DISTFILES += \
    include/astrometry/bl.ph \
    util/dallpeaks.inc \
    util/dsigma.inc \
    util/dsmooth.inc \
    util/dallpeaks.inc \
    util/dsigma.inc \
    util/dsmooth.inc \
    util/intmap.inc \
    util/resample.inc

HEADERS += \
    gsl-an/cblas/cblas.h \
    gsl-an/cblas/error_cblas.h \
    gsl-an/cblas/error_cblas_l2.h \
    gsl-an/cblas/error_cblas_l3.h \
    gsl-an/cblas/source_asum_c.h \
    gsl-an/cblas/source_asum_r.h \
    gsl-an/cblas/source_axpy_c.h \
    gsl-an/cblas/source_axpy_r.h \
    gsl-an/cblas/source_copy_c.h \
    gsl-an/cblas/source_copy_r.h \
    gsl-an/cblas/source_dot_c.h \
    gsl-an/cblas/source_dot_r.h \
    gsl-an/cblas/source_gemm_c.h \
    gsl-an/cblas/source_gemm_r.h \
    gsl-an/cblas/source_gemv_c.h \
    gsl-an/cblas/source_gemv_r.h \
    gsl-an/cblas/source_ger.h \
    gsl-an/cblas/source_gerc.h \
    gsl-an/cblas/source_geru.h \
    gsl-an/cblas/source_hemm.h \
    gsl-an/cblas/source_hemv.h \
    gsl-an/cblas/source_her.h \
    gsl-an/cblas/source_her2.h \
    gsl-an/cblas/source_her2k.h \
    gsl-an/cblas/source_herk.h \
    gsl-an/cblas/source_iamax_c.h \
    gsl-an/cblas/source_iamax_r.h \
    gsl-an/cblas/source_nrm2_c.h \
    gsl-an/cblas/source_nrm2_r.h \
    gsl-an/cblas/source_rot.h \
    gsl-an/cblas/source_rotg.h \
    gsl-an/cblas/source_rotm.h \
    gsl-an/cblas/source_rotmg.h \
    gsl-an/cblas/source_scal_c.h \
    gsl-an/cblas/source_scal_c_s.h \
    gsl-an/cblas/source_scal_r.h \
    gsl-an/cblas/source_swap_c.h \
    gsl-an/cblas/source_swap_r.h \
    gsl-an/cblas/source_symm_c.h \
    gsl-an/cblas/source_symm_r.h \
    gsl-an/cblas/source_symv.h \
    gsl-an/cblas/source_syr.h \
    gsl-an/cblas/source_syr2.h \
    gsl-an/cblas/source_syr2k_c.h \
    gsl-an/cblas/source_syr2k_r.h \
    gsl-an/cblas/source_syrk_c.h \
    gsl-an/cblas/source_syrk_r.h \
    gsl-an/cblas/source_trmm_c.h \
    gsl-an/cblas/source_trmm_r.h \
    gsl-an/cblas/source_trmv_c.h \
    gsl-an/cblas/source_trmv_r.h \
    gsl-an/cblas/source_trsm_c.h \
    gsl-an/cblas/source_trsm_r.h \
    gsl-an/cblas/source_trsv_c.h \
    gsl-an/cblas/source_trsv_r.h \
    gsl-an/gsl/gsl_blas.h \
    gsl-an/gsl/gsl_blas_types.h \
    gsl-an/gsl/gsl_block.h \
    gsl-an/gsl/gsl_block_char.h \
    gsl-an/gsl/gsl_block_complex_double.h \
    gsl-an/gsl/gsl_block_complex_float.h \
    gsl-an/gsl/gsl_block_complex_long_double.h \
    gsl-an/gsl/gsl_block_double.h \
    gsl-an/gsl/gsl_block_float.h \
    gsl-an/gsl/gsl_block_int.h \
    gsl-an/gsl/gsl_block_long.h \
    gsl-an/gsl/gsl_block_long_double.h \
    gsl-an/gsl/gsl_block_short.h \
    gsl-an/gsl/gsl_block_uchar.h \
    gsl-an/gsl/gsl_block_uint.h \
    gsl-an/gsl/gsl_block_ulong.h \
    gsl-an/gsl/gsl_block_ushort.h \
    gsl-an/gsl/gsl_cblas.h \
    gsl-an/gsl/gsl_check_range.h \
    gsl-an/gsl/gsl_complex.h \
    gsl-an/gsl/gsl_errno.h \
    gsl-an/gsl/gsl_inline.h \
    gsl-an/gsl/gsl_linalg.h \
    gsl-an/gsl/gsl_machine.h \
    gsl-an/gsl/gsl_math.h \
    gsl-an/gsl/gsl_matrix.h \
    gsl-an/gsl/gsl_matrix_char.h \
    gsl-an/gsl/gsl_matrix_complex_double.h \
    gsl-an/gsl/gsl_matrix_complex_float.h \
    gsl-an/gsl/gsl_matrix_complex_long_double.h \
    gsl-an/gsl/gsl_matrix_double.h \
    gsl-an/gsl/gsl_matrix_float.h \
    gsl-an/gsl/gsl_matrix_int.h \
    gsl-an/gsl/gsl_matrix_long.h \
    gsl-an/gsl/gsl_matrix_long_double.h \
    gsl-an/gsl/gsl_matrix_short.h \
    gsl-an/gsl/gsl_matrix_uchar.h \
    gsl-an/gsl/gsl_matrix_uint.h \
    gsl-an/gsl/gsl_matrix_ulong.h \
    gsl-an/gsl/gsl_matrix_ushort.h \
    gsl-an/gsl/gsl_message.h \
    gsl-an/gsl/gsl_minmax.h \
    gsl-an/gsl/gsl_mode.h \
    gsl-an/gsl/gsl_multiroots.h \
    gsl-an/gsl/gsl_nan.h \
    gsl-an/gsl/gsl_permutation.h \
    gsl-an/gsl/gsl_permute.h \
    gsl-an/gsl/gsl_permute_char.h \
    gsl-an/gsl/gsl_permute_complex_double.h \
    gsl-an/gsl/gsl_permute_complex_float.h \
    gsl-an/gsl/gsl_permute_complex_long_double.h \
    gsl-an/gsl/gsl_permute_double.h \
    gsl-an/gsl/gsl_permute_float.h \
    gsl-an/gsl/gsl_permute_int.h \
    gsl-an/gsl/gsl_permute_long.h \
    gsl-an/gsl/gsl_permute_long_double.h \
    gsl-an/gsl/gsl_permute_short.h \
    gsl-an/gsl/gsl_permute_uchar.h \
    gsl-an/gsl/gsl_permute_uint.h \
    gsl-an/gsl/gsl_permute_ulong.h \
    gsl-an/gsl/gsl_permute_ushort.h \
    gsl-an/gsl/gsl_permute_vector.h \
    gsl-an/gsl/gsl_permute_vector_char.h \
    gsl-an/gsl/gsl_permute_vector_complex_double.h \
    gsl-an/gsl/gsl_permute_vector_complex_float.h \
    gsl-an/gsl/gsl_permute_vector_complex_long_double.h \
    gsl-an/gsl/gsl_permute_vector_double.h \
    gsl-an/gsl/gsl_permute_vector_float.h \
    gsl-an/gsl/gsl_permute_vector_int.h \
    gsl-an/gsl/gsl_permute_vector_long.h \
    gsl-an/gsl/gsl_permute_vector_long_double.h \
    gsl-an/gsl/gsl_permute_vector_short.h \
    gsl-an/gsl/gsl_permute_vector_uchar.h \
    gsl-an/gsl/gsl_permute_vector_uint.h \
    gsl-an/gsl/gsl_permute_vector_ulong.h \
    gsl-an/gsl/gsl_permute_vector_ushort.h \
    gsl-an/gsl/gsl_pow_int.h \
    gsl-an/gsl/gsl_precision.h \
    gsl-an/gsl/gsl_sys.h \
    gsl-an/gsl/gsl_types.h \
    gsl-an/gsl/gsl_vector.h \
    gsl-an/gsl/gsl_vector_char.h \
    gsl-an/gsl/gsl_vector_complex.h \
    gsl-an/gsl/gsl_vector_complex_double.h \
    gsl-an/gsl/gsl_vector_complex_float.h \
    gsl-an/gsl/gsl_vector_complex_long_double.h \
    gsl-an/gsl/gsl_vector_double.h \
    gsl-an/gsl/gsl_vector_float.h \
    gsl-an/gsl/gsl_vector_int.h \
    gsl-an/gsl/gsl_vector_long.h \
    gsl-an/gsl/gsl_vector_long_double.h \
    gsl-an/gsl/gsl_vector_short.h \
    gsl-an/gsl/gsl_vector_uchar.h \
    gsl-an/gsl/gsl_vector_uint.h \
    gsl-an/gsl/gsl_vector_ulong.h \
    gsl-an/gsl/gsl_vector_ushort.h \
    gsl-an/matrix/view_matrix.h \
    gsl-an/multiroots/test_funcs.h \
    gsl-an/vector/view_vector.h \
    gsl-an/build.h \
    gsl-an/config.h \
    gsl-an/gsl_math.h \
    gsl-an/gsl_version.h \
    gsl-an/templates_off.h \
    gsl-an/templates_on.h \
    include/astrometry/2mass-fits.h \
    include/astrometry/2mass.h \
    include/astrometry/allquads.h \
    include/astrometry/an-bool.h \
    include/astrometry/an-endian.h \
    include/astrometry/an-opts.h \
    include/astrometry/an-thread-pthreads.h \
    include/astrometry/an-thread.h \
    include/astrometry/anqfits.h \
    include/astrometry/anwcs.h \
    include/astrometry/augment-xylist.h \
    include/astrometry/axyfile.h \
    include/astrometry/bl-nl.h \
    include/astrometry/bl-nl.inc \
    include/astrometry/bl-sort.h \
    include/astrometry/bl.h \
    include/astrometry/bl.inc \
    include/astrometry/brightstars.h \
    include/astrometry/bt.h \
    include/astrometry/build-index.h \
    include/astrometry/cairoutils.h \
    include/astrometry/catalog.h \
    include/astrometry/coadd.h \
    include/astrometry/codefile.h \
    include/astrometry/codekd.h \
    include/astrometry/codetree.h \
    include/astrometry/constellation-boundaries.h \
    include/astrometry/constellations.h \
    include/astrometry/convolve-image.h \
    include/astrometry/ctmf.h \
    include/astrometry/datalog.h \
    include/astrometry/dimage.h \
    include/astrometry/dualtree.h \
    include/astrometry/dualtree_nearestneighbour.h \
    include/astrometry/dualtree_rangesearch.h \
    include/astrometry/eigen-math.h \
    include/astrometry/engine.h \
    include/astrometry/errors.h \
    include/astrometry/fileutils.h \
    include/astrometry/fit-wcs.h \
    include/astrometry/fits-guess-scale.h \
    include/astrometry/fitsbin.h \
    include/astrometry/fitsfile.h \
    include/astrometry/fitsioutils.h \
    include/astrometry/fitstable.h \
    include/astrometry/gslutils.h \
    include/astrometry/hd.h \
    include/astrometry/healpix-utils.h \
    include/astrometry/healpix.h \
    include/astrometry/hpquads.h \
    include/astrometry/image2xy-files.h \
    include/astrometry/image2xy.h \
    include/astrometry/index.h \
    include/astrometry/indexset.h \
    include/astrometry/intmap.h \
    include/astrometry/ioutils.h \
    include/astrometry/kdtree.h \
    include/astrometry/kdtree_fits_io.h \
    include/astrometry/keywords.h \
    include/astrometry/log.h \
    include/astrometry/matchfile.h \
    include/astrometry/matchobj.h \
    include/astrometry/mathutil.h \
    include/astrometry/mathutil.inc \
    include/astrometry/merge-index.h \
    include/astrometry/multiindex.h \
    include/astrometry/new-wcs.h \
    include/astrometry/nomad-fits.h \
    include/astrometry/nomad.h \
    include/astrometry/onefield.h \
    include/astrometry/openngc.h \
    include/astrometry/os-features-config.h \
    include/astrometry/os-features.h \
    include/astrometry/permutedsort.h \
    include/astrometry/plotannotations.h \
    include/astrometry/plotfill.h \
    include/astrometry/plotgrid.h \
    include/astrometry/plothealpix.h \
    include/astrometry/plotimage.h \
    include/astrometry/plotindex.h \
    include/astrometry/plotmatch.h \
    include/astrometry/plotoutline.h \
    include/astrometry/plotradec.h \
    include/astrometry/plotxy.h \
    include/astrometry/qfits_byteswap.h \
    include/astrometry/qfits_card.h \
    include/astrometry/qfits_config.h \
    include/astrometry/qfits_convert.h \
    include/astrometry/qfits_error.h \
    include/astrometry/qfits_float.h \
    include/astrometry/qfits_header.h \
    include/astrometry/qfits_image.h \
    include/astrometry/qfits_keywords.h \
    include/astrometry/qfits_md5.h \
    include/astrometry/qfits_memory.h \
    include/astrometry/qfits_rw.h \
    include/astrometry/qfits_std.h \
    include/astrometry/qfits_table.h \
    include/astrometry/qfits_time.h \
    include/astrometry/qfits_tools.h \
    include/astrometry/qidxfile.h \
    include/astrometry/quad-builder.h \
    include/astrometry/quad-utils.h \
    include/astrometry/quadfile.h \
    include/astrometry/rdlist.h \
    include/astrometry/resample.h \
    include/astrometry/resort-xylist.h \
    include/astrometry/scamp-catalog.h \
    include/astrometry/scamp.h \
    include/astrometry/simplexy-common.h \
    include/astrometry/simplexy.h \
    include/astrometry/sip-utils.h \
    include/astrometry/sip.h \
    include/astrometry/sip_qfits.h \
    include/astrometry/solvedfile.h \
    include/astrometry/solver.h \
    include/astrometry/solverutils.h \
    include/astrometry/starkd.h \
    include/astrometry/starutil.h \
    include/astrometry/starutil.inc \
    include/astrometry/starxy.h \
    include/astrometry/tabsort.h \
    include/astrometry/thread-specific.inc \
    include/astrometry/tic.h \
    include/astrometry/tpv.h \
    include/astrometry/tweak.h \
    include/astrometry/tweak2.h \
    include/astrometry/tycho2-fits.h \
    include/astrometry/tycho2.h \
    include/astrometry/ucac3.h \
    include/astrometry/ucac4.h \
    include/astrometry/ucac5.h \
    include/astrometry/uniformize-catalog.h \
    include/astrometry/unpermute-quads.h \
    include/astrometry/unpermute-stars.h \
    include/astrometry/usnob-fits.h \
    include/astrometry/usnob.h \
    include/astrometry/verify.h \
    include/astrometry/wcs-pv2sip.h \
    include/astrometry/wcs-rd2xy.h \
    include/astrometry/wcs-xy2rd.h \
    include/astrometry/xylist.h \
    libkd/an-fls.h \
    libkd/kdint_dtype_d.h \
    libkd/kdint_dtype_f.h \
    libkd/kdint_dtype_l.h \
    libkd/kdint_dtype_s.h \
    libkd/kdint_dtype_u.h \
    libkd/kdint_etype_d.h \
    libkd/kdint_etype_f.h \
    libkd/kdint_etype_l.h \
    libkd/kdint_etype_s.h \
    libkd/kdint_etype_u.h \
    libkd/kdint_ttype_d.h \
    libkd/kdint_ttype_f.h \
    libkd/kdint_ttype_l.h \
    libkd/kdint_ttype_s.h \
    libkd/kdint_ttype_u.h \
    libkd/kdtree_internal.h \
    libkd/kdtree_internal_common.h \
    libkd/kdtree_mem.h \
    qfits-an/md5.h \
    solver/an_mm_malloc.h \
    solver/cut-table.h \
    solver/fverify.h \
    solver/lsfile.h \
    solver/noise.h \
    solver/pnpoly.h \
    solver/pquad.h \
    solver/solver.i \
    solver/startree.h \
    solver/verify2.h \
    util/boilerplate.h \
    util/cfitsutils.h \
    util/cutest.h \
    util/histogram.h \
    util/histogram2d.h \
    util/md5_util.h \
    util/sparsematrix.h \
    util/wcs-resample.h \
    include/memory.h

